### ISSUE TITLE
Different CMake and compile errors with version from master-branch.

### ISSUE THREAD

**Issue by hxrain** [ZahlGraf/IrrIMGUI#1]
CMake/SourceFiles.cmake:33
    includes/IrrIMGUI/CIMGUIHandle.h
Should be:
    includes/IrrIMGUI/IIMGUIHandle.h

**Comment by hxrain** [comment]
![image](https://cloud.githubusercontent.com/assets/11452539/10447527/bb100092-71b7-11e5-9072-b74753085827.png)
there is a lack of:
source/IReferenceCounter.cpp

**Comment by hxrain** [comment]
![image](https://cloud.githubusercontent.com/assets/11452539/10447560/03c6b3bc-71b8-11e5-9f00-ccd633e5c340.png)
if have keyword "noexcept" VS2013 compile error.

**Comment by hxrain** [comment]
Should be:
![image](https://cloud.githubusercontent.com/assets/11452539/10447958/97bc6de8-71bb-11e5-8348-6ff90e306552.png)
and
![image](https://cloud.githubusercontent.com/assets/11452539/10447965/abd127ce-71bb-11e5-8e67-c99011575018.png)
and
![image](https://cloud.githubusercontent.com/assets/11452539/10447972/c57f8814-71bb-11e5-9d58-d25c914b880d.png)

**Comment by hxrain** [comment]
me using code is old?

**Comment by ZahlGraf** [comment]
Hi,

I think you try to use the latest version from master-branch right?
I accidentally did a push from my private copy to it where I currently prepare the 0.3 Version. 
The 0.3 version will contain the classes IIMGUIHandle and IReferenceCounter, but the CMake is not adapted yet and it is completely untested. 
So please still use the 0.2 version tag, since this is the latest version that should be run out of the box.
From the feature point of view there are almost no differences. Just take care, that for 0.2 Version you still need to create a IMGUI Handle with "new CIMGUIHandle(...)" and not like in 0.3 with "createIMGUI(...)".
(Look at the samples for version 0.2). 

The issue with "noexcept" is strange, since VS2015 complains, when it is not there. I will look at this. Please just delete it locally for 0.2. In version 0.3 I will provide a solution, that only VS2015 will write "noexcept" here. 

Sorry for the confusion with the Master-Branch, I will write a comment to the main-page, that the users should use 0.2 and not the master-branch.
For further releases I will take care to not push any unfinished features to the branch. 

Best regards and thanks for telling me the issues :)

**Comment by ZahlGraf** [comment]
Created #2 to not forget to fix the "noexcept" issue.
I hope I can release 0.3 within the next week, I work every evening on it :)

**Comment by ZahlGraf** [comment]
Some Minutes ago I did a push to the master branch, so now the unstable version compiles again on VS2015 with CMake. I also adapted all Examples to the new interface. However, before I can make an official release out of it, I have to do prepare some more stuff for version 0.3

**Comment by hxrain** [comment]
ok. Thank you!

**Comment by ZahlGraf** [comment]
Version 0.3 is out now...
I tested a lot of different compilers and systems - also MSVC2013. There are no compile errors anymore and all tests and examples run out of the box.
Sorry again for the inconvenience due to messing up the master branch. 

Have a lot of fun using IrrIMGUI :)
